# Generated by Django 4.2.16 on 2024-09-07 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('ceo_name', models.CharField(max_length=300, verbose_name='CEO name')),
                ('location', models.CharField(max_length=300, verbose_name='Location')),
                ('hash_id', models.TextField(default=None, null=True, verbose_name='Hash')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'started'), (2, 'in_process'), (3, 'completed')], default=1, verbose_name='State')),
                ('title', models.CharField(max_length=500, verbose_name='Solution Title')),
                ('description', models.CharField(max_length=200, verbose_name='Project Description')),
                ('resume', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(max_length=200, verbose_name='Token')),
                ('tokens_limit', models.FloatField(default=100, verbose_name='Token Limit')),
                ('hash_id', models.TextField(default=None, null=True, verbose_name='Hash')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.company')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'Projects',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'approved'), (3, 'rejected')], default=1, verbose_name='State')),
                ('title', models.CharField(max_length=500, verbose_name='Solution Title')),
                ('description', models.TextField(verbose_name='Solution Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='solutions/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(max_length=200, verbose_name='Token Payment')),
                ('proposed_tokens', models.FloatField(default=100, verbose_name='Proposed Tokens')),
                ('hash_id', models.TextField(default=None, null=True, verbose_name='Hash')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solution',
                'verbose_name_plural': 'Solutions',
                'ordering': ('id',),
            },
        ),
    ]
