# Generated by Django 4.2.16 on 2024-09-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resume',
            field=models.FileField(default='', upload_to='projects/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=500, verbose_name='project Title'),
        ),
    ]
