# Generated by Django 4.0 on 2024-05-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='quantity',
            new_name='num_images',
        ),
    ]
